# Site settings
name: Tech Notes
email: yxxchen@ucdavis.edu
author: Yuxin Chen
url: http://yuxinxinchen.com
resume_site: 
github: https://github.com/YuxinxinChen/
baseurl: ""
description: Actually, less is more!
meta_description: Haha 
motto: Hehe
banner: Hihi

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: YuxinxinChen
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : Yuxin
    disqus :
        short_name : Yuxin
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
